### ISSUE TITLE
[Insight] YAML files should not contain syntax error - in ansible/roles/symfony/tasks/main.yml, line 14

### ISSUE THREAD

**Issue by theofidry** [CDJE/Incipio#16]
**[in ansible/roles/symfony/tasks/main.yml, line 14](https://github.com/CDJE/Incipio/blob/7ec375badcd9d152623f7f056c012ebc7023b8b0/ansible/roles/symfony/tasks/main.yml#L14)**

> Unable to parse at line 14 (near "cd /var/www/{{ symfony_src_dir }}").

```
    - path:  /var/www/{{ symfony_src_dir }}/app/logs
      owner: www-data

- name: Install composer dependencies
  shell:
    cd /var/www/{{ symfony_src_dir }}
    && composer install
  ignore_errors: true

- name:  Create database
  shell: php app/console doctrine:database:create
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/4720058c-4915-465c-8039-0bfd5fe5bf63/analyses/8)_
